In [209]:
import gensim
import pandas as pd
from gensim.models import Word2Vec

In [210]:
data = pd.read_csv("benefits.csv", encoding='ISO-8859-1')

In [211]:
names = pd.read_csv('names.csv', encoding='ISO-8859-1')

In [212]:
data

SPECIALITY
0             Amazing Psychology Facts for Life Hacks
1                   Iona Mind - Mental Health Support
2       Combat the root courses of poor mental-health
3   unlimited access to evidence-based psychologic...
4                      ÊDialectical Behavior Therapy 
5                             Mental health condition
6   Connect with your therapist on your Bravely th...
7                                    peer support app
8                                  Meditation Therapy
9                                  Mystic Mindfulness
10                                     tracking moods
11                                            therapy
12                               learning to meditate
13                                  suicide awareness
14                                            anxiety
15                                          addiction
16                                 boosting your mood
17                                   eating disorders
18                                                OCD
19                                              sleep
20                            reducing alcohol intake
21                                   quitting alcohol
22  tracking moods, creating positive thought patt...
23                                            therapy
24  learning to meditate, developing concentration...
25               suicide awareness, positive thinking
26                       stress, breathing techniques
27                anxiety,social anxiety, and phobias
28  track habits to quit smoking, drinking alcohol...
29  coping with stress, fueling your career succes...
30  encourage relaxation, alleviate tension, and r...
31  getting care for both your mental and physical...
32  safe space to talk openly about depression wit...
33  to practice helpful techniques, such as visual...
34      Êprovides you with free distant reiki healing
35  Êto show you how to reduce anxiety and to lear...
36  therapists covering a wide range of areas Ð fr...
37                                  for reiki healing
38                        ÊBalance your body and mind

In [213]:
names

APP NAME
0   Mental Health Psychology Facts
1                             Iona
2   Mindshine: Mental Health Coach
3   29k: Mental Health & Wellbeing
4       DBT Coach : Guided Therapy
5              Mental Health Tests
6                         BravelyÊ
7                       WhiteFlagÊ
8                        Breakfree
9                         Liferise
10                         MoodKit
11                       Talkspace
12                       Headspace
13             Better Stop Suicide
14                   MindShift CBT
15                      Quit That!
16                         Happify
17                 Recovery Record
18                            NOCD
19                            Calm
20                         Reframe
21                      I Am Sober
22                         MoodKit
23                       Talkspace
24                       Headspace
25             Better Stop Suicide
26                        iBreathe
27                   MindShift CBT
28                      Quit That!
29                         Happify
30                            Calm
31                          Amwell
32                        Talklife
33                        Sanvello
34                   Vitamin Reiki
35         Anxiety Relief Hypnosis
36              BetterHelp-Therapy
37                        ReikiAll
38    Chakras-Meditation & Healing

In [ ]:
names['APP NAME']

In [215]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
corpus = []
for i in range(0, len(data.SPECIALITY)):
  processed_data = re.sub('[^a-zA-Z]', ' ', data['SPECIALITY'][i])
  processed_data = processed_data.lower()
  processed_data = processed_data.split()
  all_stopwords = stopwords.words('english')
  processed_data = [word for word in processed_data if not word in set(all_stopwords)]
  processed_data = ' '.join(processed_data)
  corpus.append(processed_data)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [216]:
for i in range(0,len(data.SPECIALITY)):
  data['SPECIALITY'][i] = corpus[i]

In [ ]:
data

In [218]:
final = data.SPECIALITY.apply(gensim.utils.simple_preprocess) #Convert a document into a list of lowercase tokens, ignoring tokens that are too short or too long.

In [219]:
final

0             [amazing, psychology, facts, life, hacks]
1                 [iona, mind, mental, health, support]
2         [combat, root, courses, poor, mental, health]
3     [unlimited, access, evidence, based, psycholog...
4                      [dialectical, behavior, therapy]
5                           [mental, health, condition]
6          [connect, therapist, bravely, therapy, home]
7                                  [peer, support, app]
8                                 [meditation, therapy]
9                                 [mystic, mindfulness]
10                                    [tracking, moods]
11                                            [therapy]
12                                 [learning, meditate]
13                                 [suicide, awareness]
14                                            [anxiety]
15                                          [addiction]
16                                     [boosting, mood]
17                                  [eating, dis

In [220]:
len(final)

39

In [221]:
connected_dataset = [] #list of asanas Asanas according to the respective number of cleaned words.

In [222]:
for i in range(len(final)):
  for j in range(len(final[i])):
    connected_dataset.append(names['APP NAME'][i])

In [223]:
len(connected_dataset)

160

In [224]:
connected_dataset

['Mental Health Psychology Facts',
 'Mental Health Psychology Facts',
 'Mental Health Psychology Facts',
 'Mental Health Psychology Facts',
 'Mental Health Psychology Facts',
 'Iona',
 'Iona',
 'Iona',
 'Iona',
 'Iona',
 'Mindshine: Mental Health Coach',
 'Mindshine: Mental Health Coach',
 'Mindshine: Mental Health Coach',
 'Mindshine: Mental Health Coach',
 'Mindshine: Mental Health Coach',
 'Mindshine: Mental Health Coach',
 '29k: Mental Health & Wellbeing',
 '29k: Mental Health & Wellbeing',
 '29k: Mental Health & Wellbeing',
 '29k: Mental Health & Wellbeing',
 '29k: Mental Health & Wellbeing',
 '29k: Mental Health & Wellbeing',
 'DBT Coach : Guided Therapy',
 'DBT Coach : Guided Therapy',
 'DBT Coach : Guided Therapy',
 'Mental Health Tests',
 'Mental Health Tests',
 'Mental Health Tests',
 'BravelyÊ',
 'BravelyÊ',
 'BravelyÊ',
 'BravelyÊ',
 'BravelyÊ',
 'WhiteFlagÊ',
 'WhiteFlagÊ',
 'WhiteFlagÊ',
 'Breakfree',
 'Breakfree',
 'Liferise',
 'Liferise',
 'MoodKit',
 'MoodKit',
 'Talks

In [225]:
model = Word2Vec(sentences = final, sg=1, min_count=1, vector_size = 31, workers=4, window = 5)

In [226]:
model.train(final, total_examples=model.corpus_count, epochs=1500)

(108021, 240000)

In [227]:
model.wv['amazing']

array([-0.56615716,  0.06996328,  0.0324352 , -0.85976213, -1.1422919 ,
       -0.03646541, -0.7917265 , -0.8779858 ,  0.03010808,  0.99134594,
        1.3701482 , -0.7826137 ,  0.95951396, -0.48806965,  0.5556336 ,
        0.5045476 ,  0.16075258, -0.18193437,  0.10958986,  0.52231   ,
        0.32177207,  0.31099105,  0.87001824, -0.6845717 ,  1.1736872 ,
       -0.6286884 ,  0.15946923,  0.31904417, -0.65563494,  0.21614683,
        0.6605371 ], dtype=float32)

In [228]:
# len(model.wv.vocab)

In [229]:
# model.wv.word_vec('pain') #another way to get embeddings of a word.

In [230]:
final[0][0]

'amazing'

In [231]:
model.wv.most_similar("depression", topn = 20 )

[('others', 0.8780654072761536),
 ('wide', 0.8735957741737366),
 ('therapists', 0.8710403442382812),
 ('safe', 0.8708930611610413),
 ('range', 0.8707239031791687),
 ('covering', 0.8684459328651428),
 ('areas', 0.8679915070533752),
 ('openly', 0.8674009442329407),
 ('talk', 0.8670714497566223),
 ('space', 0.865974485874176),
 ('anxiety', 0.6291895508766174),
 ('phobias', 0.5967236161231995),
 ('social', 0.5832989811897278),
 ('mood', 0.4863893687725067),
 ('disorders', 0.4855770468711853),
 ('show', 0.4785613715648651),
 ('learn', 0.475796103477478),
 ('balance', 0.4718502163887024),
 ('body', 0.4655904173851013),
 ('reduce', 0.46144816279411316)]

In [232]:
embeddings_dash = []
for i in range(len(final)):
  for j in final[i]:
    embeddings_dash.append(model.wv[j])

In [233]:
len(embeddings_dash)

160

In [234]:
embeddings_dash[0]

array([-0.56615716,  0.06996328,  0.0324352 , -0.85976213, -1.1422919 ,
       -0.03646541, -0.7917265 , -0.8779858 ,  0.03010808,  0.99134594,
        1.3701482 , -0.7826137 ,  0.95951396, -0.48806965,  0.5556336 ,
        0.5045476 ,  0.16075258, -0.18193437,  0.10958986,  0.52231   ,
        0.32177207,  0.31099105,  0.87001824, -0.6845717 ,  1.1736872 ,
       -0.6286884 ,  0.15946923,  0.31904417, -0.65563494,  0.21614683,
        0.6605371 ], dtype=float32)

In [235]:
import numpy as np

In [236]:
# for i in range(len(embeddings_dash)):
#   embeddings_dash[i] = np.pad(embeddings_dash[i],(6,6)) #when we one hot encoded the asanas, its number is elements were 32. therefore we pad 6 zeros in front and 6 at the back.

In [237]:
len(embeddings_dash[0])

31

In [238]:
embeddings_dash[0]

array([-0.56615716,  0.06996328,  0.0324352 , -0.85976213, -1.1422919 ,
       -0.03646541, -0.7917265 , -0.8779858 ,  0.03010808,  0.99134594,
        1.3701482 , -0.7826137 ,  0.95951396, -0.48806965,  0.5556336 ,
        0.5045476 ,  0.16075258, -0.18193437,  0.10958986,  0.52231   ,
        0.32177207,  0.31099105,  0.87001824, -0.6845717 ,  1.1736872 ,
       -0.6286884 ,  0.15946923,  0.31904417, -0.65563494,  0.21614683,
        0.6605371 ], dtype=float32)

In [239]:
final[0][0]

'amazing'

In [240]:
import numpy as np
embeddings_dash = np.array(embeddings_dash)

In [241]:
embeddings_dash

array([[-0.56615716,  0.06996328,  0.0324352 , ..., -0.65563494,
         0.21614683,  0.6605371 ],
       [-0.49719906,  0.05510577,  0.12343346, ..., -0.6235037 ,
         0.3059844 ,  0.7801773 ],
       [-0.55068475, -0.00814274,  0.06619054, ..., -0.70800906,
         0.21008077,  0.69766873],
       ...,
       [ 0.46613514, -0.03992984,  0.34279746, ..., -0.33721548,
         0.76970226,  0.04915211],
       [ 0.32290617, -0.04116223,  0.31639016, ..., -0.22651762,
         0.47613436, -0.33373642],
       [ 0.33850574,  0.3422302 ,  0.48944548, ..., -0.29459375,
         0.84693676,  0.15983115]], dtype=float32)

In [242]:
def one_hot(array):
    unique, inverse = np.unique(array, return_inverse=True)
    onehot = np.eye(unique.shape[0])[inverse]
    return onehot

In [243]:
arr = one_hot(connected_dataset)

In [244]:
output = arr

In [245]:
output

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [246]:
len(output)

160

In [247]:
input = embeddings_dash

In [248]:
len(input)

160

In [249]:
input.shape

(160, 31)

In [250]:
output.shape = input.shape

In [251]:
output.shape

(160, 31)

In [252]:
import tensorflow as tf

In [253]:
ann = tf.keras.models.Sequential()

In [254]:
ann.add(tf.keras.layers.Dense(220, activation='relu'))

In [255]:
ann.add(tf.keras.layers.Dense(units=31, activation='softmax'))

In [256]:
ann.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [260]:
ann.fit(input, output, batch_size = 5, epochs = 1000)

Epoch 1/1000
32/32 [==============================] - 0s 6ms/step - loss: 0.4227 - accuracy: 0.7437
Epoch 2/1000
32/32 [==============================] - 0s 6ms/step - loss: 0.4256 - accuracy: 0.7750
Epoch 3/1000
32/32 [==============================] - 0s 7ms/step - loss: 0.4172 - accuracy: 0.7250
Epoch 4/1000
32/32 [==============================] - 0s 6ms/step - loss: 0.4274 - accuracy: 0.7563
Epoch 5/1000
32/32 [==============================] - 0s 8ms/step - loss: 0.4254 - accuracy: 0.7500
Epoch 6/1000
32/32 [==============================] - 0s 9ms/step - loss: 0.4251 - accuracy: 0.7437
Epoch 7/1000
32/32 [==============================] - 0s 5ms/step - loss: 0.4231 - accuracy: 0.7437
Epoch 8/1000
32/32 [==============================] - 0s 5ms/step - loss: 0.4334 - accuracy: 0.7500
Epoch 9/1000
32/32 [==============================] - 0s 4ms/step - loss: 0.4111 - accuracy: 0.7750
Epoch 10/1000
32/32 [==============================] - 0s 4ms/step - loss: 0.4268 - accuracy: 0.7563

In [258]:
test = []
test.append(model.wv['healing'])
test.append(model.wv['stress'])
test.append(model.wv['mind'])
test = np.array(test)
test

array([[-0.39226252, -0.2275617 ,  1.1355913 ,  0.2242478 , -0.8037857 ,
        -0.1803555 , -0.7111139 , -0.38184133,  1.1341147 ,  0.14478442,
         0.4066924 , -0.30585682,  0.47037446,  0.06635071,  0.6681364 ,
         0.21714595,  0.11227991, -0.8147389 , -0.49426967,  0.1948514 ,
         1.1912194 ,  0.03041521, -0.21320088, -0.43952364,  1.1931571 ,
        -0.8365659 ,  0.53095543,  0.5184596 ,  1.0223541 ,  0.14944991,
        -0.04468414],
       [ 0.9319349 ,  1.1309735 ,  0.4758862 , -0.25855616, -0.70967436,
        -0.3680297 , -0.1023157 , -0.00164514, -0.30195573,  0.670327  ,
         0.6036219 , -0.1306709 , -0.47449625,  0.42133126,  0.497108  ,
        -0.43576202, -0.21575664,  0.34665698, -1.212119  , -0.10835215,
         0.5334274 ,  0.10264542,  0.8250068 ,  0.8280582 ,  0.82770616,
        -1.4861531 , -0.16900939,  0.20375073, -0.16204447,  0.39424792,
        -0.7876226 ],
       [ 0.33850574,  0.3422302 ,  0.48944548, -0.9941019 ,  0.18051453,
       

In [259]:
for i in range(len(names['APP NAME'])):
  for j in ann.predict(test):
    if i == np.argmax(j):
      print(names['APP NAME'][i])

1/1 [==============================] - 0s 23ms/step
WhiteFlagÊ
1/1 [==============================] - 0s 26ms/step
Better Stop Suicide
1/1 [==============================] - 0s 23ms/step
Quit That!
1/1 [==============================] - 0s 29ms/step
